# Generated by Django 5.1.6 on 2025-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
